import rtconfig
Import('RTT_ROOT')
from building import *

# get current directory
cwd = GetCurrentDir()

src = Split("""
HAL_Driver/Src/hal.c
HAL_Driver/Src/hal_cortex.c
HAL_Driver/Src/hal_rcc.c
HAL_Driver/Src/hal_dma.c
HAL_Driver/Src/hal_gpio.c
HAL_Driver/Src/hal_uart.c
HAL_Driver/Src/hal_exti.c
""")


libpath = ['.', cwd + '/Device', cwd + '/HAL_Driver/Src']
libs = ["System_Accelerate",]

path = [cwd + '/HAL_Driver/Inc',
    cwd + '/Device',
    cwd + '/CMSIS']

group = DefineGroup('ACM32_HAL', src, depend = [''], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')
